development: &dev
  adapter: postgresql
  database: <%= Rails.application.class.parent_name.underscore %>_development
  host: localhost
  port: <%= ENV['BOXEN_POSTGRESQL_PORT'] || 5432 %>
  pool: 5
  timeout: 5000

test:
  <<: *dev
  database: <%= Rails.application.class.parent_name.underscore %>_test
